// String constants
CLEANING_STATE_READY = 'CLEANING_STATE_READY';
CLEANING_STATE_CLEANING = 'CLEANING_STATE_CLEANING';
CLEANING_STATE_COMPLETE = 'CLEANING_STATE_COMPLETE';
CLEANING_STATE_HALTING = 'CLEANING_STATE_HALTING';